#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LUA_PATH="$LUA_PATH;./?.lua;$DIR/?.lua;$DIR/rigel/?.lua;$DIR/rigel/src/?.lua;$DIR/rigel/misc/?.lua;$DIR/rigel/examples/?.lua;;" TERRA_PATH="./?.t;$DIR/rigel/?.t;$DIR/rigel/src/?.t;$DIR/rigel/misc/?.t;$DIR/rigel/examples/?.t" terra "$@"
